### ISSUE TITLE
Auto reconnect on RemoteException & RunLater

### ISSUE THREAD

**Issue by Schuler0893** [fhhagenberg-sqe-esd-ws21/elevator-control-center-team-a#30]
Write robust code that automatically reconnects to the RMI API whenever the connection gets lost, i.e. a RemoteException is thrown on calling any of the IElevator methods).

**Comment by geruempel** [comment]
TODO:
 - InitElevatorAndFloors wenn möglich aus GUI-Konstruktor entfernen
 - gui wenn möglich nicht neu erstellen nach verbindungsabbruch sondern nur reInit
 - Exceptions aufräumen
